# Continuous integration tasks running on Cirrus CI.
#

env:
  WXRUBY_TEST_EXCLUDE: 'test_intl:test_media_ctrl'
  GITHUB_TOKEN: ENCRYPTED[!d9f8c8d7b73dd043f3d5f287caaedad4530509c511cfb4aaf9e4582b2f6b4e3962fea59108f1dc396774e7887452fa85!]

pr_1_task:
  timeout_in: 90m
  skip: "changesIncludeOnly('.yardopts', '.cirrus.yml', 'LICENSE','*.md','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb', 'tools/**')"
  only_if: $CIRRUS_PR != ''
  matrix:
    - name: Cirrus CI / Fedora ARM64 Test
      arm_container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / Debian AMD64 Release
      container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: LinuxMint AMD64 Test
      container:
        image: linuxmintd/mint22-amd64
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a
    cat /etc/os-release

  system_build_script: |
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh

    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log    

  system_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh

pr_2_task:
  timeout_in: 90m
  skip: "changesIncludeOnly('.yardopts', '.cirrus.yml', 'LICENSE','*.md','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb', 'tools/**')"
  only_if: $CIRRUS_PR != ''
  matrix:
    - name: Cirrus CI / OpenSuSE Leap AMD64 Test
      container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / ArchLinux AMD64 Test
      container:
        image: archlinux/archlinux:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: arch

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a
    cat /etc/os-release

  latest_build_script: |
    ./tools/scripts/cirrus/setup-ruby-install-latest.sh

    ./tools/scripts/cirrus/build-wxruby3.sh --latest 2>&1 | tee -a build-wxruby3.log

  latest_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh

verify_1_task:
  timeout_in: 90m
  skip: "changesIncludeOnly('.yardopts', '.cirrus.yml', 'LICENSE','*.md','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb', 'tools/**')"
  only_if: $CIRRUS_BRANCH =~ 'master' && $CIRRUS_BUILD_SOURCE != 'api'
  matrix:
    - name: Cirrus CI / Fedora AMD64 Test
      container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / Debian ARM64 Test
      arm_container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: Cirrus CI / Ubuntu AMD64 Test
      container:
        image: ubuntu:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: ubuntu

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a
    cat /etc/os-release

  system_build_script: |
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh

    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log    

  system_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh

verify_2_task:
  timeout_in: 90m
  skip: "changesIncludeOnly('.yardopts', '.cirrus.yml', 'LICENSE','*.md','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb', 'tools/**')"
  only_if: $CIRRUS_BRANCH =~ 'master' && $CIRRUS_BUILD_SOURCE != 'api'
  matrix:
    - name: Cirrus CI / OpenSuSE Leap ARM64 Test
      arm_container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / ArchLinux AMD64 Test
      container:
        image: archlinux/archlinux:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: arch

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a
    cat /etc/os-release

  latest_build_script: |
    ./tools/scripts/cirrus/setup-ruby-install-latest.sh

    ./tools/scripts/cirrus/build-wxruby3.sh --latest 2>&1 | tee -a build-wxruby3.log

  latest_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh
