# Continuous integration tasks running on Cirrus CI.
#

env:
  WXRUBY_TEST_EXCLUDE: 'test_intl:test_media_ctrl'
  GITHUB_TOKEN: ENCRYPTED[2ce3914266dec78118dd9706c25d2e52fbd164f86713692efde9b8af5f0159099cb299934a8d6279e524da7a0790e025]

pr_task:
  timeout_in: 90m
  skip: "changesIncludeOnly('.yardopts','*.md','.circleci/**','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb')"
  only_if: $CIRRUS_PR != ''
  matrix:
    - name: Cirrus CI / Fedora ARM64 Test
      arm_container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / OpenSuSE Leap AMD64 Test
      container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / Debian ARM64 Test
      arm_container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: Cirrus CI / MacOSX Ventura M1 Release
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-xcode:latest
      env:
        osname: darwin
        distro: macosx

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a

  system_build_script: |
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh

    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log    

  system_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh

  system_cleanup_script: |
    ./tools/scripts/cirrus/cleanup-wxruby3.sh
    
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh remove

  latest_build_script:
    ./tools/scripts/cirrus/setup-ruby-install-latest.sh

    ./tools/scripts/cirrus/build-wxruby3.sh --latest 2>&1 | tee -a build-wxruby3.log

  latest_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh

verify_task:
  timeout_in: 90m
  skip: "changesIncludeOnly('.yardopts','*.md','.circleci/**','.github/**','lib/wx/doc/**','assets/**','lib/wx/version.rb')"
  only_if: $CIRRUS_BRANCH =~ 'master' && $CIRRUS_BUILD_SOURCE != 'api'
  matrix:
    - name: Cirrus CI / Fedora AMD64 Test
      container:
        image: fedora:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: fedora
    - name: Cirrus CI / OpenSuSE Leap AMD64 Test
      container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / OpenSuSE Leap ARM64 Test
      arm_container:
        image: opensuse/leap:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: opensuse
    - name: Cirrus CI / Debian AMD64 Test
      container:
        image: debian:latest
        cpu: 4
        memory: 8G
      env:
        osname: linux
        distro: debian
    - name: Cirrus CI / MacOSX Sonoma M1 Release
      macos_instance:
        image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
      env:
        osname: darwin
        distro: macosx

  before_script: |
    ./tools/scripts/cirrus/setup-$distro.sh

    # Show some information about the system.
    uname -a
    locale
    locale -a

  system_build_script: |
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh

    ./tools/scripts/cirrus/build-wxruby3.sh 2>&1 | tee -a build-wxruby3.log    

  system_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh

  system_cleanup_script: |
    ./tools/scripts/cirrus/cleanup-wxruby3.sh
    
    ./tools/scripts/cirrus/setup-$distro-system-ruby.sh remove

  latest_build_script:
    ./tools/scripts/cirrus/setup-ruby-install-latest.sh

    ./tools/scripts/cirrus/build-wxruby3.sh --latest 2>&1 | tee -a build-wxruby3.log

  latest_test_script:
    ./tools/scripts/cirrus/test-wxruby3.sh
