= wxRuby3 Objects and Lifecycles

== wxRuby3 Objects

The wxRuby3 library consists (almost entirely) of Ruby classes wrapping native C++ wxWidgets classes and types.
The instances of these classes (almost) always create a split object with both a Ruby instance (VALUE) part and
a C++ instance (pointer) part. In the context of this document these instances are the 'wxRuby3 Objects'.
Wrapping code is generated by way of the SWIG tool which includes standard methods for object tracking (maintaining
the link between Ruby and C++ object parts).

Management of these objects can be either the responsibility of the Ruby GC (Garbage Collection) process or of
C++ processes (like window destruction).

Enums, constants and global variables are excepted from this setup and are 'wrapped' in a much simpler way providing
a more direct bidirectional mapping between Ruby and C++ values.

== Tracking

During the lifetime of a wxRuby3 Object it may pass the boundary between C++ and Ruby (or vice versa) multiple times.
In the cases where the Ruby counterpart provides additional or overloaded functionality (either through a derived class
definition or object extension) it is vital to maintain the link between C++ and Ruby counterparts such that when mapping
a C++ instance to it's Ruby counterpart instance the same Ruby instance can be retrieved (with the same state). The
information for maintaining the link is also used to keep the Ruby instance counterpart alive when not visible to
Ruby GC marking anymore.

For other objects (pure data, reference counted, non-extensible objects) this link does not matter and no tracking is
required, In these cases the mapping from a C++ instance to it's Ruby counterpart instance will always result in a new
untracked Ruby instance (one-shot short-lived objects).

== Lifecycle variants

There are a number of lifecycle variants for these wxRuby3 objects.

singleton objects::
 These objects will exist while the application's main event loop executes and can be managed by either Ruby (when
 created in Ruby and no handoff to C\++ occurred) or C++ (when created in C++ and only referenced in Ruby).

window objects::
 Windows are **always** managed in C\++ whether they are created in Ruby or in C++. In most cases a (toplevel) window
 will be destroyed when closed and in turn will destroy all it's child window (recursively). An event handler tracking
 destruction events will take care of cleaning up tracking registries. +
 In selected cases (dialogs and windows that are not closed but hidden) explicit calls are required to destroy a window.

dialog objects::
 Windows that **always** need an explicit call to destroy. wxRuby3 provides convenience methods to make this more
 automatic.

monitored objects::
 Objects managed in either Ruby or in C\++ for which wxRuby3 is able to monitor destruction in C\++ (either directly by
 way of having a derived C++ class with a special destructor method or some such or indirectly by way of capturing events)
 and subsequently clean up tracking registries.

unmonitored objects::
 Objects managed in either Ruby or in C\++ for which wxRuby3 is **unable** to monitor destruction in C++. Extra care is
 needed in these cases for Ruby GC marking to make sure to only access C++ counterparts for objects that are still
 managed in Ruby.

value objects::
 Objects for which the C++ counterpart will never be handed over to C++ and always remain managed by Ruby. Instead when
 passing these objects to C++ a readonly reference is passed in or a copy will be made. This includes pure data objects
 (size, rect etc.) as well as reference counted C++ objects (bitmap, icon, cursor, font etc.)


== Object categories

=== Singletons

Singleton objects can either be managed in Ruby or in C++ and will exist while the application's
main event loop executes.

.Singletons
|===
|Object |Lifecycle |Description

|Wx::App
|singleton
|Application instance. Tracked in a global variable. Triggers GC marking for other (non-singleton)
 objects.

|Wx::Clipboard
|singleton
|Clipboard instance. Created and managed in C++. Not tracked.
|===

=== Windows

Window objects can either be created in Ruby or in C++. Management is always left to C++ (OnDestroy).
Tracked by SWIG's tracking code.

.Windows
|===
|Object |Lifecycle|Description

|Wx::Window derivatives except Wx::Dialog (and derived) and Wx::MenuBar
|window
|Tracked by SWIG's tracking code. Managed in C++. Tracking cleanup occurs when windows are destroyed which happens
automatically for toplevel windows like Wx::Frame when they are closed. All child windows of a
windows being destroyed will be destroyed as well.
GC marking of tracked Ruby values is triggered through the Wx::App singleton.

|Wx::Dialog derivatives.
|window
|Tracked by SWIG's tracking code. Managed in C++. Tracking cleanup occurs when windows are destroyed which does
not happen automatically but requires explicit calls to `#destroy`. All child windows of a
dialog being destroyed will be destroyed as well.
GC marking of tracked Ruby values is triggered through the Wx::App singleton.

|Wx::MenuBar
|monitored
|Tracked by custom tracking code through derived C++ class. Managed in Ruby as long as not assigned to a managing window.
Managed in C++ after window assignment. Tracking cleanup happens either on Ruby GC for Ruby managed
instances or on C++ destruction through the managing window destruction.
GC marking of tracked Ruby values is triggered either through regular Ruby GC marking or through
the Wx::App singleton for assigned menu bars.
|===

=== Events

.Events
|===
|Object |Lifecycle|Description

|Standard wxWidgets Wx::Event derivatives
|unmonitored
|These objects are normally created in C++ as a response to user actions and only appear in Ruby event handler contexts
as temporary Ruby objects and always remain managed by C++. On rare occasions they can be created in Ruby and handed over
to C++. The Ruby object counter parts are tracked using the SWIG tracking registry. Tracking registry cleanup is fully
driven by Ruby GC.

|Wx::Event and Wx::CommandEvent user defined Ruby derivatives
|monitored
|Created in Ruby. Managed in either Ruby or C++ (after handoff). Tracking (cleanup) through custom C++ monitoring code.
|===

=== Event handlers

.Event handlers
|===
|Object |Lifecycle |Description

|Wx::EvtHandler
|unmonitored
|

|event handler callbacks
|monitored
|

|async callbacks
|monitored
|

|===

=== Device contexts

=== Graphics context

=== Menu and menu items

.Menus
|===
|Object |Lifecycle |Description

|Wx::Menu
|monitored
|

|Wx::MenuItem
|unmonitored
|
|===

=== Common window properties

These objects are typically created in Ruby and subsequently assigned to window objects. As long as they are unassigned
the objects will be managed by Ruby but after assigment management passes to C++ (linked to window destruction). Extra
care needs to be taken for most of these objects as there is no automatic cleanup of tracking registries on C++ destruction.

.Common Windows Properties
|===
|Object |Description

|Wx::Sizer and derivatives
|

|Wx::Caret
|

|Wx::DropTarget
|

|Wx::Validator
|
|===

=== Other Window properties

Properties of derived windows like PropertyGrid and PGProperties.

=== Variants

=== Reference counted objects

Untracked objects linking to C++ reference counted objects. Always managed by Ruby. Objects returned by wxRuby wrappers
will always be Ruby managed copies.

- Wx::Pen
- Wx::Brush
- Wx::Bitmap
- Wx::BitmapBundle
- Wx::Icon
- Wx::IconBundle
- Wx::Image
- Wx::Cursor
- Wx::Colour
- Wx::Font
- Wx::FontData
- Wx::Palette
- Wx::Animation
- Wx::Region
- Wx::AcceleratorTable
- Wx::GraphicsObject (and derivatives)

=== Unmanaged objects

Untracked pure data objects. Always passed by value.

- Wx::Rect
- Wx::Size
- Wx::Point
- Wx::RealPoint
- Wx::Point2DInt
- Wx::Point2DDouble
- Wx::Rect2DDouble
