# :stopdoc:
# This file is automatically generated by the WXRuby3 documentation
# generator. Do not alter this file.
# :startdoc:


module Wx

  class GenericAnimationCtrl < AnimationCtrl

    # This override of {Wx::AnimationCtrl#play} lets you specify if the animation must loop or not.
    # @param looped [Boolean] default true
    # @return [Boolean]
    def play(looped = true) end

  end

end
