module Wx

=begin
  These constants are not documented in the wxWidgets interface headers
  although they are referenced in various argument defaults which *are*
  in the interface header declarations so we do want them included the
  wxRuby docs so the doc links work but we do not need them in the
  wxRuby implementation since these are internal to the C++ wrappers.
=end

  DefaultDateTimeFormat = '%c'
  DefaultTimeSpanFormat = '%H:%M:%S'

  ChoiceNameStr = 'choice'
  ColourPickerCtrlNameStr = 'colourpicker'
  ColourPickerWidgetNameStr = 'colourpickerwidget'
  HyperlinkCtrlNameStr = 'hyperlink'
  PanelNameStr = 'panel'
  ListBoxNameStr = 'listBox'
  FrameNameStr = 'frame'
  StatusLineNameStr = 'status_line'
  StaticBitmapNameStr = 'staticBitmap'
  WebViewNameStr = 'webView'
  AnimationCtrlNameStr = 'animationctrl'
  ToolBarNameStr = 'toolbar'
  TextCtrlNameStr = 'text'
  ListCtrlNameStr = 'listCtrl'
  FilePickerCtrlNameStr = 'filepicker'
  FilePickerWidgetNameStr = 'filepickerwidget'
  DirPickerCtrlNameStr = 'dirpicker'
  DirPickerWidgetNameStr = 'dirpickerwidget'
  FileCtrlNameStr = 'wxfilectrl'
  StaticBoxNameStr = 'groupBox'
  ButtonNameStr = 'button'
  RadioBoxNameStr = 'radioBox'
  StaticLineNameStr = 'staticLine'
  RadioButtonNameStr = 'radioButton'
  BitmapRadioButtonNameStr = 'radioButton'
  GaugeNameStr = 'gauge'
  DataViewCtrlNameStr = 'dataviewCtrl'
  FontPickerCtrlNameStr = 'fontpicker'
  FontPickerWidgetNameStr = 'fontpickerwidget'
  RearrangeListNameStr = 'rearrangeList'
  RearrangeDialogNameStr = 'rearrangeDlg'
  NotebookNameStr = 'notebook'
  ControlNameStr = 'control'
  ScrollBarNameStr = 'scrollBar'
  StatusBarNameStr = 'statusBar'
  SliderNameStr = 'slider'
  HeaderCtrlNameStr = 'wxHeaderCtrl'
  BitmapComboBoxNameStr = 'bitmapComboBox'
  CheckBoxNameStr = 'check'
  FileDialogNameStr = 'filedlg'
  AddRemoveCtrlNameStr = 'addRemoveCtrl'
  StaticTextNameStr = 'staticText'
  ComboBoxNameStr = 'comboBox'
  SearchCtrlNameStr = 'searchCtrl'
  DirDialogNameStr = 'dirCtrl'
  TreeCtrlNameStr = 'treeCtrl'
  DialogNameStr = 'dialog'
  CollapsibleHeaderCtrlNameStr = 'collapsibleHeader'
  CollapsiblePaneNameStr = 'collapsiblePane'
  BannerWindowNameStr = 'bannerwindow'
  GridNameStr = 'grid'
  TreeListCtrlNameStr = 'treeListCtrl'
  EditableListBoxNameStr = 'editableListBox'
  VListBoxNameStr = 'vListBox'
  CollapsiblePaneNameStr = 'collapsiblePane'
  MSWHeaderCtrlNameStr = 'mswHeaderCtrl'
  PropertyGridManagerNameStr = 'propertyGridManager'
  PropertyGridNameStr = 'propertyGrid'
  STCNameStr = 'stcwindow'

end
