
module Wx

  EVT_COMMAND_SCROLL_TOP = EVT_SCROLL_TOP         
  EVT_COMMAND_SCROLL_BOTTOM = EVT_SCROLL_BOTTOM      
  EVT_COMMAND_SCROLL_LINEUP = EVT_SCROLL_LINEUP      
  EVT_COMMAND_SCROLL_LINEDOWN = EVT_SCROLL_LINEDOWN    
  EVT_COMMAND_SCROLL_PAGEUP = EVT_SCROLL_PAGEUP      
  EVT_COMMAND_SCROLL_PAGEDOWN = EVT_SCROLL_PAGEDOWN    
  EVT_COMMAND_SCROLL_THUMBTRACK = EVT_SCROLL_THUMBTRACK  
  EVT_COMMAND_SCROLL_THUMBRELEASE = EVT_SCROLL_THUMBRELEASE
  EVT_COMMAND_SCROLL_CHANGED = EVT_SCROLL_CHANGED     
  
end
