/**
 * This file is automatically generated by the WXRuby3 interface generator.
 * Do not alter this file.
 */

%include "../common.i"

%module(directors="1") <%= spec.module_name %>
GC_MANAGE_AS_OBJECT(wxClientDC);

%import "include/wxObject.h"
%import "include/wxDC.h"
%import "include/wxWindowDC.h"


%include "include/wxClientDC.h"
