/**
 * This file is automatically generated by the WXRuby3 interface generator.
 * Do not alter this file.
 */
         
#ifdef __WXAPP_H_INCLUDED__
#define __WXAPP_H_INCLUDED__

class wxApp : wxEvtHandler
{
private:
  wxApp();
public:
#ifdef __WXOSX__
  // from virtual void wxApp::MacNewFile
  virtual void MacNewFile();
#endif
#ifdef __WXOSX__
  // from virtual void wxApp::MacOpenFiles
  virtual void MacOpenFiles(const wxArrayString &fileNames);
#endif
#ifdef __WXOSX__
  // from virtual void wxApp::MacOpenFile
  virtual void MacOpenFile(const wxString &fileName);
#endif
#ifdef __WXOSX__
  // from virtual void wxApp::MacOpenURL
  virtual void MacOpenURL(const wxString &url);
#endif
#ifdef __WXOSX__
  // from virtual void wxApp::MacPrintFile
  virtual void MacPrintFile(const wxString &fileName);
#endif
#ifdef __WXOSX__
  // from virtual void wxApp::MacReopenApp
  virtual void MacReopenApp();
#endif
#ifdef __WXOSX__
  // from virtual bool wxApp::OSXIsGUIApplication
  virtual bool OSXIsGUIApplication();
#endif
#ifdef __WXOSX__
  // from void wxApp::OSXEnableAutomaticTabbing
  void OSXEnableAutomaticTabbing(bool enable);
#endif
#ifdef __WXGTK__
  // from static void wxApp::GTKSuppressDiagnostics
  void GTKSuppressDiagnostics(int flags=-1);
#endif
  // from wxApp::wxApp
   wxApp();
  virtual wxApp();
  // from virtual wxVideoMode wxApp::GetDisplayMode
  virtual wxVideoMode GetDisplayMode() const;
  // from bool wxApp::GetExitOnFrameDelete
  bool GetExitOnFrameDelete() const;
  // from virtual wxLayoutDirection wxApp::GetLayoutDirection
  virtual wxLayoutDirection GetLayoutDirection() const;
  // from bool wxApp::GetUseBestVisual
  bool GetUseBestVisual() const;
  // from virtual wxWindow * wxApp::GetTopWindow
  virtual wxWindow * GetTopWindow() const;
  // from virtual bool wxApp::IsActive
  virtual bool IsActive() const;
  // from virtual bool wxApp::SafeYield
  virtual bool SafeYield(wxWindow *win, bool onlyIfNeeded);
  // from virtual bool wxApp::SafeYieldFor
  virtual bool SafeYieldFor(wxWindow *win, long eventsToProcess);
  // from virtual bool wxApp::SetDisplayMode
  virtual bool SetDisplayMode(const wxVideoMode &info);
  // from void wxApp::SetExitOnFrameDelete
  void SetExitOnFrameDelete(bool flag);
  // from virtual bool wxApp::SetNativeTheme
  virtual bool SetNativeTheme(const wxString &theme);
  // from void wxApp::SetTopWindow
  void SetTopWindow(wxWindow *window);
  // from void wxApp::SetUseBestVisual
  void SetUseBestVisual(bool flag, bool forceTrueColour=false);
  // from static wxWindow * wxApp::GetMainTopWindow
  wxWindow * GetMainTopWindow();
  // from wxString wxAppConsole::GetAppDisplayName
  wxString GetAppDisplayName() const;
  // from wxString wxAppConsole::GetAppName
  wxString GetAppName() const;
  // from wxString wxAppConsole::GetClassName
  wxString GetClassName() const;
  // from wxAppTraits * wxAppConsole::GetTraits
  wxAppTraits * GetTraits();
  // from const wxString & wxAppConsole::GetVendorDisplayName
  const wxString & GetVendorDisplayName() const;
  // from const wxString & wxAppConsole::GetVendorName
  const wxString & GetVendorName() const;
  // from void wxAppConsole::SetAppDisplayName
  void SetAppDisplayName(const wxString &name);
  // from void wxAppConsole::SetAppName
  void SetAppName(const wxString &name);
  // from void wxAppConsole::SetClassName
  void SetClassName(const wxString &name);
  // from void wxAppConsole::SetVendorDisplayName
  void SetVendorDisplayName(const wxString &name);
  // from void wxAppConsole::SetVendorName
  void SetVendorName(const wxString &name);
  // from void wxAppConsole::SetCLocale
  void SetCLocale();
  // from virtual void wxAppConsole::ExitMainLoop
  virtual void ExitMainLoop();
  // from virtual int wxAppConsole::FilterEvent
  virtual int FilterEvent(wxEvent &event);
  // from virtual bool wxAppConsole::UsesEventLoop
  virtual bool UsesEventLoop() const;
  // from virtual void wxAppConsole::ProcessPendingEvents
  virtual void ProcessPendingEvents();
  // from void wxAppConsole::DeletePendingEvents
  void DeletePendingEvents();
  // from bool wxAppConsole::HasPendingEvents
  bool HasPendingEvents() const;
  // from void wxAppConsole::SuspendProcessingOfPendingEvents
  void SuspendProcessingOfPendingEvents();
  // from void wxAppConsole::ResumeProcessingOfPendingEvents
  void ResumeProcessingOfPendingEvents();
  // from bool wxAppConsole::Yield
  bool Yield(bool onlyIfNeeded=false);
  // from static bool wxAppConsole::IsMainLoopRunning
  bool IsMainLoopRunning();
  // from virtual void wxAppConsole::OnAssertFailure
  virtual void OnAssertFailure(const wxChar *file, int line, const wxChar *func, const wxChar *cond, const wxChar *msg);
  // from virtual int wxAppConsole::OnExit
  virtual int OnExit();
  // from virtual bool wxAppConsole::OnInit
  virtual bool OnInit();
  // from virtual int wxAppConsole::OnRun
  virtual int OnRun();
};




#endif /* __WXAPP_H_INCLUDED__ */