/**
 * This file is automatically generated by the WXRuby3 interface generator.
 * Do not alter this file.
 */
         
#ifdef __WXCLIENTDC_H_INCLUDED__
#define __WXCLIENTDC_H_INCLUDED__

class wxClientDC : wxWindowDC
{
private:
  wxClientDC();
public:
  // from wxClientDC::wxClientDC
   wxClientDC(wxWindow *window);
};




#endif /* __WXCLIENTDC_H_INCLUDED__ */