/**
 * This file is automatically generated by the WXRuby3 interface generator.
 * Do not alter this file.
 */
         
#ifdef __WXDC_H_INCLUDED__
#define __WXDC_H_INCLUDED__

class wxDC : wxObject
{
private:
  wxDC();
public:
  // from wxCoord wxDC::DeviceToLogicalX
  wxCoord DeviceToLogicalX(wxCoord x) const;
  // from wxCoord wxDC::DeviceToLogicalXRel
  wxCoord DeviceToLogicalXRel(wxCoord x) const;
  // from wxCoord wxDC::DeviceToLogicalY
  wxCoord DeviceToLogicalY(wxCoord y) const;
  // from wxCoord wxDC::DeviceToLogicalYRel
  wxCoord DeviceToLogicalYRel(wxCoord y) const;
  // from wxCoord wxDC::LogicalToDeviceX
  wxCoord LogicalToDeviceX(wxCoord x) const;
  // from wxCoord wxDC::LogicalToDeviceXRel
  wxCoord LogicalToDeviceXRel(wxCoord x) const;
  // from wxCoord wxDC::LogicalToDeviceY
  wxCoord LogicalToDeviceY(wxCoord y) const;
  // from wxCoord wxDC::LogicalToDeviceYRel
  wxCoord LogicalToDeviceYRel(wxCoord y) const;
  // from wxPoint wxDC::DeviceToLogical
  wxPoint DeviceToLogical(wxCoord x, wxCoord y) const;
  // from wxPoint wxDC::DeviceToLogical
  wxPoint DeviceToLogical(const wxPoint &pt) const;
  // from wxSize wxDC::DeviceToLogicalRel
  wxSize DeviceToLogicalRel(int x, int y) const;
  // from wxSize wxDC::DeviceToLogicalRel
  wxSize DeviceToLogicalRel(const wxSize &dim) const;
  // from wxPoint wxDC::LogicalToDevice
  wxPoint LogicalToDevice(wxCoord x, wxCoord y) const;
  // from wxPoint wxDC::LogicalToDevice
  wxPoint LogicalToDevice(const wxPoint &pt) const;
  // from wxSize wxDC::LogicalToDeviceRel
  wxSize LogicalToDeviceRel(int x, int y) const;
  // from wxSize wxDC::LogicalToDeviceRel
  wxSize LogicalToDeviceRel(const wxSize &dim) const;
  // from void wxDC::Clear
  void Clear();
  // from void wxDC::DrawArc
  void DrawArc(wxCoord xStart, wxCoord yStart, wxCoord xEnd, wxCoord yEnd, wxCoord xc, wxCoord yc);
  // from void wxDC::DrawArc
  void DrawArc(const wxPoint &ptStart, const wxPoint &ptEnd, const wxPoint &centre);
  // from void wxDC::DrawBitmap
  void DrawBitmap(const wxBitmap &bitmap, wxCoord x, wxCoord y, bool useMask=false);
  // from void wxDC::DrawBitmap
  void DrawBitmap(const wxBitmap &bmp, const wxPoint &pt, bool useMask=false);
  // from void wxDC::DrawCheckMark
  void DrawCheckMark(wxCoord x, wxCoord y, wxCoord width, wxCoord height);
  // from void wxDC::DrawCheckMark
  void DrawCheckMark(const wxRect &rect);
  // from void wxDC::DrawCircle
  void DrawCircle(wxCoord x, wxCoord y, wxCoord radius);
  // from void wxDC::DrawCircle
  void DrawCircle(const wxPoint &pt, wxCoord radius);
  // from void wxDC::DrawEllipse
  void DrawEllipse(wxCoord x, wxCoord y, wxCoord width, wxCoord height);
  // from void wxDC::DrawEllipse
  void DrawEllipse(const wxPoint &pt, const wxSize &size);
  // from void wxDC::DrawEllipse
  void DrawEllipse(const wxRect &rect);
  // from void wxDC::DrawEllipticArc
  void DrawEllipticArc(wxCoord x, wxCoord y, wxCoord width, wxCoord height, double start, double end);
  // from void wxDC::DrawEllipticArc
  void DrawEllipticArc(const wxPoint &pt, const wxSize &sz, double sa, double ea);
  // from void wxDC::DrawIcon
  void DrawIcon(const wxIcon &icon, wxCoord x, wxCoord y);
  // from void wxDC::DrawIcon
  void DrawIcon(const wxIcon &icon, const wxPoint &pt);
  // from void wxDC::DrawLabel
  void DrawLabel(const wxString &text, const wxBitmap &bitmap, const wxRect &rect, int alignment=wxALIGN_LEFT|wxALIGN_TOP, int indexAccel=-1, wxRect *rectBounding=NULL);
  // from void wxDC::DrawLabel
  void DrawLabel(const wxString &text, const wxRect &rect, int alignment=wxALIGN_LEFT|wxALIGN_TOP, int indexAccel=-1);
  // from void wxDC::DrawLine
  void DrawLine(wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2);
  // from void wxDC::DrawLine
  void DrawLine(const wxPoint &pt1, const wxPoint &pt2);
  // from void wxDC::DrawLines
  void DrawLines(int n, const wxPoint points[], wxCoord xoffset=0, wxCoord yoffset=0);
  // from void wxDC::DrawPoint
  void DrawPoint(wxCoord x, wxCoord y);
  // from void wxDC::DrawPoint
  void DrawPoint(const wxPoint &pt);
  // from void wxDC::DrawPolygon
  void DrawPolygon(int n, const wxPoint points[], wxCoord xoffset=0, wxCoord yoffset=0, wxPolygonFillMode fill_style=wxODDEVEN_RULE);
  // from void wxDC::DrawPolyPolygon
  void DrawPolyPolygon(int n, const int count[], const wxPoint points[], wxCoord xoffset=0, wxCoord yoffset=0, wxPolygonFillMode fill_style=wxODDEVEN_RULE);
  // from void wxDC::DrawRectangle
  void DrawRectangle(wxCoord x, wxCoord y, wxCoord width, wxCoord height);
  // from void wxDC::DrawRectangle
  void DrawRectangle(const wxPoint &pt, const wxSize &sz);
  // from void wxDC::DrawRectangle
  void DrawRectangle(const wxRect &rect);
  // from void wxDC::DrawRotatedText
  void DrawRotatedText(const wxString &text, wxCoord x, wxCoord y, double angle);
  // from void wxDC::DrawRotatedText
  void DrawRotatedText(const wxString &text, const wxPoint &point, double angle);
  // from void wxDC::DrawRoundedRectangle
  void DrawRoundedRectangle(wxCoord x, wxCoord y, wxCoord width, wxCoord height, double radius);
  // from void wxDC::DrawRoundedRectangle
  void DrawRoundedRectangle(const wxPoint &pt, const wxSize &sz, double radius);
  // from void wxDC::DrawRoundedRectangle
  void DrawRoundedRectangle(const wxRect &rect, double radius);
  // from void wxDC::DrawSpline
  void DrawSpline(int n, const wxPoint points[]);
  // from void wxDC::DrawSpline
  void DrawSpline(const wxPointList *points);
  // from void wxDC::DrawSpline
  void DrawSpline(wxCoord x1, wxCoord y1, wxCoord x2, wxCoord y2, wxCoord x3, wxCoord y3);
  // from void wxDC::DrawText
  void DrawText(const wxString &text, wxCoord x, wxCoord y);
  // from void wxDC::DrawText
  void DrawText(const wxString &text, const wxPoint &pt);
  // from void wxDC::GradientFillConcentric
  void GradientFillConcentric(const wxRect &rect, const wxColour &initialColour, const wxColour &destColour);
  // from void wxDC::GradientFillConcentric
  void GradientFillConcentric(const wxRect &rect, const wxColour &initialColour, const wxColour &destColour, const wxPoint &circleCenter);
  // from void wxDC::GradientFillLinear
  void GradientFillLinear(const wxRect &rect, const wxColour &initialColour, const wxColour &destColour, wxDirection nDirection=wxRIGHT);
  // from bool wxDC::FloodFill
  bool FloodFill(wxCoord x, wxCoord y, const wxColour &colour, wxFloodFillStyle style=wxFLOOD_SURFACE);
  // from bool wxDC::FloodFill
  bool FloodFill(const wxPoint &pt, const wxColour &col, wxFloodFillStyle style=wxFLOOD_SURFACE);
  // from void wxDC::CrossHair
  void CrossHair(wxCoord x, wxCoord y);
  // from void wxDC::CrossHair
  void CrossHair(const wxPoint &pt);
  // from void wxDC::DestroyClippingRegion
  void DestroyClippingRegion();
  // from bool wxDC::GetClippingBox
  bool GetClippingBox(wxCoord *x, wxCoord *y, wxCoord *width, wxCoord *height) const;
  // from bool wxDC::GetClippingBox
  bool GetClippingBox(wxRect &rect) const;
  // from void wxDC::SetClippingRegion
  void SetClippingRegion(wxCoord x, wxCoord y, wxCoord width, wxCoord height);
  // from void wxDC::SetClippingRegion
  void SetClippingRegion(const wxPoint &pt, const wxSize &sz);
  // from void wxDC::SetClippingRegion
  void SetClippingRegion(const wxRect &rect);
  // from void wxDC::SetDeviceClippingRegion
  void SetDeviceClippingRegion(const wxRegion &region);
  // from wxCoord wxDC::GetCharHeight
  wxCoord GetCharHeight() const;
  // from wxCoord wxDC::GetCharWidth
  wxCoord GetCharWidth() const;
  // from wxFontMetrics wxDC::GetFontMetrics
  wxFontMetrics GetFontMetrics() const;
  // from void wxDC::GetMultiLineTextExtent
  void GetMultiLineTextExtent(const wxString &string, wxCoord *w, wxCoord *h, wxCoord *heightLine=NULL, const wxFont *font=NULL) const;
  // from wxSize wxDC::GetMultiLineTextExtent
  wxSize GetMultiLineTextExtent(const wxString &string) const;
  // from void wxDC::GetTextExtent
  void GetTextExtent(const wxString &string, wxCoord *w, wxCoord *h, wxCoord *descent=NULL, wxCoord *externalLeading=NULL, const wxFont *font=NULL) const;
  // from wxSize wxDC::GetTextExtent
  wxSize GetTextExtent(const wxString &string) const;
  // from int wxDC::GetBackgroundMode
  int GetBackgroundMode() const;
  // from const wxFont & wxDC::GetFont
  const wxFont & GetFont() const;
  // from wxLayoutDirection wxDC::GetLayoutDirection
  wxLayoutDirection GetLayoutDirection() const;
  // from const wxColour & wxDC::GetTextBackground
  const wxColour & GetTextBackground() const;
  // from const wxColour & wxDC::GetTextForeground
  const wxColour & GetTextForeground() const;
  // from void wxDC::SetBackgroundMode
  void SetBackgroundMode(int mode);
  // from void wxDC::SetFont
  void SetFont(const wxFont &font);
  // from void wxDC::SetTextBackground
  void SetTextBackground(const wxColour &colour);
  // from void wxDC::SetTextForeground
  void SetTextForeground(const wxColour &colour);
  // from void wxDC::SetLayoutDirection
  void SetLayoutDirection(wxLayoutDirection dir);
  // from void wxDC::CalcBoundingBox
  void CalcBoundingBox(wxCoord x, wxCoord y);
  // from wxCoord wxDC::MaxX
  wxCoord MaxX() const;
  // from wxCoord wxDC::MaxY
  wxCoord MaxY() const;
  // from wxCoord wxDC::MinX
  wxCoord MinX() const;
  // from wxCoord wxDC::MinY
  wxCoord MinY() const;
  // from void wxDC::ResetBoundingBox
  void ResetBoundingBox();
  // from bool wxDC::StartDoc
  bool StartDoc(const wxString &message);
  // from void wxDC::EndDoc
  void EndDoc();
  // from void wxDC::EndPage
  void EndPage();
  // from bool wxDC::Blit
  bool Blit(wxCoord xdest, wxCoord ydest, wxCoord width, wxCoord height, wxDC *source, wxCoord xsrc, wxCoord ysrc, wxRasterOperationMode logicalFunc=wxCOPY, bool useMask=false, wxCoord xsrcMask=wxDefaultCoord, wxCoord ysrcMask=wxDefaultCoord);
  // from bool wxDC::StretchBlit
  bool StretchBlit(wxCoord xdest, wxCoord ydest, wxCoord dstWidth, wxCoord dstHeight, wxDC *source, wxCoord xsrc, wxCoord ysrc, wxCoord srcWidth, wxCoord srcHeight, wxRasterOperationMode logicalFunc=wxCOPY, bool useMask=false, wxCoord xsrcMask=wxDefaultCoord, wxCoord ysrcMask=wxDefaultCoord);
  // from const wxBrush & wxDC::GetBackground
  const wxBrush & GetBackground() const;
  // from const wxBrush & wxDC::GetBrush
  const wxBrush & GetBrush() const;
  // from const wxPen & wxDC::GetPen
  const wxPen & GetPen() const;
  // from void wxDC::SetBackground
  void SetBackground(const wxBrush &brush);
  // from void wxDC::SetBrush
  void SetBrush(const wxBrush &brush);
  // from void wxDC::SetPen
  void SetPen(const wxPen &pen);
  // from void wxDC::CopyAttributes
  void CopyAttributes(const wxDC &dc);
  // from double wxDC::GetContentScaleFactor
  double GetContentScaleFactor() const;
  // from int wxDC::GetDepth
  int GetDepth() const;
  // from wxPoint wxDC::GetDeviceOrigin
  wxPoint GetDeviceOrigin() const;
  // from wxRasterOperationMode wxDC::GetLogicalFunction
  wxRasterOperationMode GetLogicalFunction() const;
  // from wxMappingMode wxDC::GetMapMode
  wxMappingMode GetMapMode() const;
  // from bool wxDC::GetPixel
  bool GetPixel(wxCoord x, wxCoord y, wxColour *colour) const;
  // from wxSize wxDC::GetPPI
  wxSize GetPPI() const;
  // from wxSize wxDC::FromDIP
  wxSize FromDIP(const wxSize &sz) const;
  // from wxPoint wxDC::FromDIP
  wxPoint FromDIP(const wxPoint &pt) const;
  // from int wxDC::FromDIP
  int FromDIP(int d) const;
  // from wxSize wxDC::ToDIP
  wxSize ToDIP(const wxSize &sz) const;
  // from wxPoint wxDC::ToDIP
  wxPoint ToDIP(const wxPoint &pt) const;
  // from int wxDC::ToDIP
  int ToDIP(int d) const;
  // from void wxDC::GetSize
  void GetSize(wxCoord *width, wxCoord *height) const;
  // from wxSize wxDC::GetSize
  wxSize GetSize() const;
  // from void wxDC::GetSizeMM
  void GetSizeMM(wxCoord *width, wxCoord *height) const;
  // from wxSize wxDC::GetSizeMM
  wxSize GetSizeMM() const;
  // from void wxDC::GetUserScale
  void GetUserScale(double *x, double *y) const;
  // from bool wxDC::IsOk
  bool IsOk() const;
  // from void wxDC::SetAxisOrientation
  void SetAxisOrientation(bool xLeftRight, bool yBottomUp);
  // from void wxDC::SetDeviceOrigin
  void SetDeviceOrigin(wxCoord x, wxCoord y);
  // from void wxDC::SetLogicalFunction
  void SetLogicalFunction(wxRasterOperationMode function);
  // from void wxDC::SetMapMode
  void SetMapMode(wxMappingMode mode);
  // from void wxDC::SetPalette
  void SetPalette(const wxPalette &palette);
  // from void wxDC::SetUserScale
  void SetUserScale(double xScale, double yScale);
  // from bool wxDC::CanUseTransformMatrix
  bool CanUseTransformMatrix() const;
  // from bool wxDC::SetTransformMatrix
  bool SetTransformMatrix(const wxAffineMatrix2D &matrix);
  // from wxAffineMatrix2D wxDC::GetTransformMatrix
  wxAffineMatrix2D GetTransformMatrix() const;
  // from void wxDC::ResetTransformMatrix
  void ResetTransformMatrix();
  // from bool wxDC::CanDrawBitmap
  bool CanDrawBitmap() const;
  // from bool wxDC::CanGetTextExtent
  bool CanGetTextExtent() const;
  // from void * wxDC::GetHandle
  void * GetHandle() const;
  // from wxBitmap wxDC::GetAsBitmap
  wxBitmap GetAsBitmap(const wxRect *subrect=NULL) const;
  // from void wxDC::SetLogicalScale
  void SetLogicalScale(double x, double y);
  // from void wxDC::GetLogicalScale
  void GetLogicalScale(double *x, double *y) const;
  // from void wxDC::SetLogicalOrigin
  void SetLogicalOrigin(wxCoord x, wxCoord y);
  // from void wxDC::GetLogicalOrigin
  void GetLogicalOrigin(wxCoord *x, wxCoord *y) const;
  // from wxPoint wxDC::GetLogicalOrigin
  wxPoint GetLogicalOrigin() const;
  // from virtual wxGraphicsContext * wxDC::GetGraphicsContext
  virtual wxGraphicsContext * GetGraphicsContext() const;
  // from virtual void wxDC::SetGraphicsContext
  virtual void SetGraphicsContext(wxGraphicsContext *ctx);
};



// from enum wxRasterOperationMode
%constant int wxCLEAR = wxCLEAR;
%constant int wxXOR = wxXOR;
%constant int wxINVERT = wxINVERT;
%constant int wxOR_REVERSE = wxOR_REVERSE;
%constant int wxAND_REVERSE = wxAND_REVERSE;
%constant int wxCOPY = wxCOPY;
%constant int wxAND = wxAND;
%constant int wxAND_INVERT = wxAND_INVERT;
%constant int wxNO_OP = wxNO_OP;
%constant int wxNOR = wxNOR;
%constant int wxEQUIV = wxEQUIV;
%constant int wxSRC_INVERT = wxSRC_INVERT;
%constant int wxOR_INVERT = wxOR_INVERT;
%constant int wxNAND = wxNAND;
%constant int wxOR = wxOR;
%constant int wxSET = wxSET;

// from enum wxFloodFillStyle
%constant int wxFLOOD_SURFACE = wxFLOOD_SURFACE;
%constant int wxFLOOD_BORDER = wxFLOOD_BORDER;

// from enum wxMappingMode
%constant int wxMM_TEXT = wxMM_TEXT;
%constant int wxMM_METRIC = wxMM_METRIC;
%constant int wxMM_LOMETRIC = wxMM_LOMETRIC;
%constant int wxMM_TWIPS = wxMM_TWIPS;
%constant int wxMM_POINTS = wxMM_POINTS;


#endif /* __WXDC_H_INCLUDED__ */