name: docker-verify
author: martin
description: 'Linux verification builds using docker'
inputs:
  distro:  # id of input
    description: 'What distribution docker image to use'
    required: true
    default: 'ubuntu'
  ruby:
    description: 'What ruby version to use: system or latest'
    required: false
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.distro }}
    - ${{ inputs.ruby }}
