name: linux-docker-verify
author: martin
description: 'Linux docker verification build setup'
inputs:
  distro:  # id of input
    description: 'What distribution docker image to use'
    required: true
    default: 'ubuntu'
  ruby:
    description: 'What ruby version to use: system or latest'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: 'Setup Dockerfile'
      shell: bash
      run: |
        cp ${{ github.action_path }}/docker-verify/${{ inputs.distro }}/Dockerfile ${{ github.action_path }}/docker-verify/Dockerfile
    - uses: ./.github/actions/linux-docker-verify/docker-verify
      id: verify-run
      with:
        distro: ${{ inputs.distro }}
        ruby: ${{ inputs.ruby }}
