#--------------------------------------------------------------------
# @file    interfaces.rb
# @author  Martin Corino
#
# @brief   wxRuby3 wxWidgets interface generation specs
#
# @copyright Copyright (c) M.J.N. Corino, The Netherlands
#--------------------------------------------------------------------

module WXRuby3

  SPECIFICATIONS = [
    Director.Spec('Wx', 'defs'),
    Director.Spec('Wx', 'wxGDICommon'),
    Director.Spec('Wx', 'wxColour'),
    Director.Spec('Wx', 'wxObject'),
    Director.Spec('Wx', 'wxEvent'),
    Director.Spec('Wx', 'wxEvtHandler'),
    Director.Spec('Wx', 'wxApp'),
    Director.Spec('Wx', 'wxDC'),
    Director.Spec('Wx', 'wxWindowDC'),
    Director.Spec('Wx', 'wxClientDC'),
    Director.Spec('Wx', 'wxPaintDC'),
    Director.Spec('Wx', 'wxMemoryDC'),
    Director.Spec('Wx', 'wxWindow'),
    Director.Spec('Wx', 'wxNonOwnedWindow', director: Director::Window),
    Director.Spec('Wx', 'wxTopLevelWindow'),
    Director.Spec('Wx', 'wxFrame'),
    Director.Spec('Wx', 'wxGDIObject'),
    Director.Spec('Wx', 'wxIconLocation'),
    Director.Spec('Wx', 'wxMask'),
    Director.Spec('Wx', 'wxBitmap'),
    Director.Spec('Wx', 'wxIcon'),
    Director.Spec('Wx', 'wxAccelerator'),
    Director.Spec('Wx', 'wxMenuItem'),
    Director.Spec('Wx', 'wxMenuBar'),
    Director.Spec('Wx', 'wxMenu'),
    Director.Spec('Wx', 'wxAboutDialogInfo'),
    Director.Spec('Wx', 'wxDialog'),
    Director.Spec('Wx', 'wxMessageDialog', director: Director::TopLevelWindow),
    Director.Spec('Wx', 'wxSizerItem'),
    Director.Spec('Wx', 'wxSizer'),
    Director.Spec('Wx', 'wxBoxSizer', director: Director::Sizer),
    Director.Spec('Wx', 'wxControl', director: Director::Window),
    Director.Spec('Wx', 'wxTextCtrl'),
    Director.Spec('Wx', 'wxCheckBox', director: Director::Window),
    Director.Spec('Wx', 'wxAnyButton', director: Director::Window),
    Director.Spec('Wx', 'wxButton'),
    Director.Spec('Wx', 'wxToggleButton'),
    Director.Spec('Wx', 'wxControlWithItems'),
    Director.Spec('Wx', 'wxComboBox'),
    Director.Spec('Wx', 'wxRadioBox'),
    Director.Spec('Wx', 'wxPanel'),
    Director.Spec('Wx', 'wxBookCtrlEvent'),
    Director.Spec('Wx', 'wxBookCtrlBase', director: Director::BookCtrls),
    Director.Spec('Wx', 'wxNotebook', director: Director::BookCtrls),
    Director.Spec('Wx', 'wxImageList'),
    Director.Spec('Wx', 'wxListBox'),
    Director.Spec('Wx', 'wxChoice'),
    Director.Spec('Wx', 'wxStaticBox', director: Director::Window),
    Director.Spec('Wx', 'wxGauge', director: Director::Window),
    Director.Spec('Wx', 'wxSlider', director: Director::Window),
    Director.Spec('Wx', 'wxStaticText', director: Director::Window),
    Director.Spec('Wx', 'wxSpinButton', director: Director::Window),
    Director.Spec('Wx', 'wxSpinEvent'),
    Director.Spec('Wx', 'wxSpinCtrl', director: Director::Window),
    Director.Spec('Wx', 'wxStaticBitmap'),
    Director.Spec('Wx', 'wxBitmapButton', director: Director::Button),
    Director.Spec('Wx', 'wxArtProvider'),
    Director.Spec('Wx', 'wxStaticBoxSizer', director: Director::Sizer),
    Director.Spec('Wx', 'wxCursor'),
    Director.Spec('Wx', 'wxRadioButton', director: Director::Window),
    Director.Spec('Wx', 'wxToolTip'),
    Director.Spec('Wx', 'wxLog'),
    Director.Spec('Wx', 'wxRichTextEvent'),
    Director.Spec('Wx', 'wxRichTextBuffer'),
    Director.Spec('Wx', 'wxRichTextCtrl'),
    Director.Spec('Wx', 'wxToolBar'),
    Director.Spec('Wx', 'wxImage'),
    Director.Spec('Wx', 'wxDragImage'),
    Director.Spec('Wx', 'wxRichTextFileHandler'),
    Director.Spec('Wx', 'wxRichTextXMLHandler', director: Director::RichTextFileHandler),
    Director.Spec('Wx', 'wxRichTextHTMLHandler', director: Director::RichTextFileHandler),
    Director.Spec('Wx', 'wxFont'),
    Director.Spec('Wx', 'wxFontData'),
    Director.Spec('Wx', 'wxFontDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxFileDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxLocale'),
    Director.Spec('Wx', 'wxStyledTextEvent'),
    Director.Spec('Wx', 'wxStyledTextCtrl'),
    Director.Spec('Wx', 'wxSystemSettings'),
    Director.Spec('Wx', 'wxPropertySheetDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxScrolledWindow', director: Director::ScrolledT),
    Director.Spec('Wx', 'wxScrolledCanvas', director: Director::ScrolledT),
    Director.Spec('Wx', 'wxFindReplaceData'),
    Director.Spec('Wx', 'wxFindReplaceDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxFindDialogEvent'),
    Director.Spec('Wx', 'wxToolbook', director: Director::BookCtrls),
    Director.Spec('Wx', 'wxColourData'),
    Director.Spec('Wx', 'wxColourDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxTextEntryDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxSingleChoiceDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxMultiChoiceDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxTipProvider'),
    Director.Spec('Wx', 'wxDirDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxProgressDialog', director: Director::Dialog),
    Director.Spec('Wx', 'wxWindowDisabler'),
    Director.Spec('Wx', 'wxBusyInfo'),
  ]

end # module WXRuby3
