# :stopdoc:
# This file is automatically generated by the WXRuby3 documentation 
# generator. Do not alter this file.
# :startdoc:


module Wx::PG

  class NumericPropertyValidator < TextValidator

    # @overload initialize(validator)
    #   Copy constructor.
    #   @param [Wx::wxNumericPropertyValidator] validator validator to copy
    # @overload initialize(numericType, base=10)
    #   @param numericType [Wx::wxNumericPropertyValidator::NumericType]
    #   @param base [Integer]
    #   @return [Wx::PG::NumericPropertyValidator]
    def initialize(*args) end

  end # NumericPropertyValidator
  

end
