# :stopdoc:
# This file is automatically generated by the WXRuby3 documentation 
# generator. Do not alter this file.
# :startdoc:


module Wx::PG

  class NumericPropertyValidator < TextValidator

    # @overload initialize(validator)
    #   Copy constructor.
    #   @param [Wx::wxNumericPropertyValidator] validator validator to copy
    # @overload initialize(numericType, base=10)
    #   @param numericType [Wx::wxNumericPropertyValidator::NumericType]
    #   @param base [Integer]
    #   @return [Wx::PG::NumericPropertyValidator]
    def initialize(*args) end

    # Returns the value store attribute. Initially an empty string.
    # @return [String]
    def get_value; end
    alias :value :get_value

    # Sets the value store attribute.
    # @param [String] val
    def set_value(val) end
    alias :value= :set_value

  end # NumericPropertyValidator
  

end
