###
# wxRuby3 rake file
# Copyright (c) M.J.N. Corino, The Netherlands
###

require 'rake/clean'

namespace :wxruby do

  require_relative './build'

  #############################
  # public tasks

  task :build => ['config:bootstrap', :enum_list, *all_build_targets]

  desc "Compile object files from SWIG-generated sources"
  task :compile => ['config:bootstrap', *all_compile_targets]

  desc "Force a compile of object files from C++ sources"
  task :recompile => ['config:bootstrap', :clean, :compile]

  desc "Generate C++ source and header files using SWIG"
  task :swig   => ['config:bootstrap', WXRuby3.config.classes_path, :enum_list, *all_swig_targets]

  task :clean => [:clean_bin, :clean_src, *all_clean_targets] do
    rm_if(Dir[File.join(WXRuby3.config.interface_dir, '*')])
    rmdir_if(WXRuby3.config.interface_dir)
    rm_if(Dir[File.join(WXRuby3.config.common_dir, '*')])
    rmdir_if(WXRuby3.config.common_dir)
    rm_if(Dir[File.join(WXRuby3.config.classes_dir, '*')])
    rm_if(Dir[File.join(WXRuby3.config.rake_deps_dir, '.*.rake')])
    rmdir_if(WXRuby3.config.rake_deps_dir)
    rm_if(Dir[File.join(WXRuby3.config.src_gen_dir, '*')])
    rmdir_if(WXRuby3.config.src_gen_dir)
    rmdir_if(WXRuby3.config.src_dir)
  end

  desc "Delete C++ source and header files generated by SWIG"
  task :clean_src do
    rm_if(Dir[File.join(WXRuby3.config.src_dir, '*.{cpp,h}')])
  end

  desc "Force generate C++ source and header files using SWIG"
  task :reswig => ['config:bootstrap', :clean_src, :swig]

  desc "Delete compiled libraries and object files"
  task :clean_bin do
    rm_if(Dir[File.join(WXRuby3.config.rb_lib_dir, '*.so')])
    rm_if(Dir[File.join(WXRuby3.config.obj_dir, '*')])
    rmdir_if(WXRuby3.config.obj_dir)
  end

  Rake::Task[:clobber].enhance(['wxruby:clean_all'])

end

desc "Create the binary Ruby library file"
task :build => 'wxruby:build'

desc "Delete SWIG interfaces, C++ sources, library and object files"
task :clean => 'wxruby:clean'
