name: Linux Docker WXGTK builds

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'assets/**'
      - 'tools/**'
      - 'lib/wx/doc/**'
      - 'lib/wx/version.rb'
      - '**.md'
      - '.cirrus.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'assets/**'
      - 'tools/**'
      - 'lib/wx/doc/**'
      - 'lib/wx/version.rb'
      - 'rakelib/lib/**/*.yaml'
      - '**.md'
      - 'Gemfile'
      - '.yardopts'
      - '.gitignore'
      - 'LICENSE'
      - '.cirrus.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-pr:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
            target_distro: fedora
            target_base: 'latest'
            target_ruby: system
          - os: ubuntu-24.04
            arch: x86_64
            target_distro: opensuse
            target_docker_image: ['opensuse', 'leap']
            target_base: 'latest'
            target_ruby: system
          - os: ubuntu-24.04
            arch: x86_64
            target_distro: ubuntu
            target_docker_image: ['linuxmintd', 'mint22.3-amd64']
            target_base: 'latest'
            target_ruby: system
          - os: ubuntu-24.04-arm
            arch: arm64
            target_distro: debian
            target_base: '12'
            target_ruby: system
          - os: ubuntu-24.04
            arch: x86_64
            target_distro: arch
            target_docker_image: ['archlinux', 'archlinux']
            target_base: 'latest'
            target_ruby: latest
    runs-on: ${{ matrix.os }}
    name: ${{ case(matrix.target_docker_image != '', join(matrix.target_docker_image, '/'), matrix.target_distro) }}:${{ matrix.target_base }} ${{ matrix.arch }} ruby=${{ matrix.target_ruby }}
    steps:
    - name: Checkout wxRuby3
      uses: actions/checkout@v6

    - name: Setup Dockerfile
      run: |
        ${{ github.workspace }}/tools/scripts/docker/create-docker-file.sh ${{ case(matrix.target_docker_image != '', join(matrix.target_docker_image, '/'), matrix.target_distro) }} ${{ matrix.target_base }} ${{ github.workspace }}/.github/actions/linux-docker-verify/Dockerfile

    - name: Verify wxRuby3 on docker image
      uses: ./.github/actions/linux-docker-verify
      id: verify
      with:
        distro: ${{ matrix.target_distro }}
        ruby: ${{ matrix.target_ruby }}

  build-pr-merge:
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            arch: x86_64
            target_distro: manjaro
            target_docker_image: ['manjarolinux', 'base']
            target_base: 'latest'
            target_ruby: system
          - os: ubuntu-24.04
            arch: x86_64
            target_distro: debian
            target_base: 'latest'
            target_ruby: latest
          - os: ubuntu-24.04-arm
            arch: arm64
            target_distro: fedora
            target_base: '42'
            target_ruby: latest
          - os: ubuntu-24.04-arm
            arch: arm64
            target_distro: opensuse
            target_docker_image: ['opensuse', 'leap']
            target_base: '15.6'
            target_ruby: latest
    runs-on: ${{ matrix.os }}
    name: ${{ case(matrix.target_docker_image != '', join(matrix.target_docker_image, '/'), matrix.target_distro) }}:${{ matrix.target_base }} ${{ matrix.arch }} ruby=${{ matrix.target_ruby }}
    steps:
      - name: Checkout wxRuby3
        uses: actions/checkout@v6

      - name: Setup Dockerfile
        run: |
          ${{ github.workspace }}/tools/scripts/docker/create-docker-file.sh ${{ case(matrix.target_docker_image != '', join(matrix.target_docker_image, '/'), matrix.target_distro) }} ${{ matrix.target_base }} ${{ github.workspace }}/.github/actions/linux-docker-verify/Dockerfile

      - name: Verify wxRuby3 on docker image
        uses: ./.github/actions/linux-docker-verify
        id: verify
        with:
          distro: ${{ matrix.target_distro }}
          ruby: ${{ matrix.target_ruby }}
